// Generated by gencpp from file kumpulan_msgs/arduino_it.msg
// DO NOT EDIT!


#ifndef KUMPULAN_MSGS_MESSAGE_ARDUINO_IT_H
#define KUMPULAN_MSGS_MESSAGE_ARDUINO_IT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kumpulan_msgs
{
template <class ContainerAllocator>
struct arduino_it_
{
  typedef arduino_it_<ContainerAllocator> Type;

  arduino_it_()
    : distance(0)
    , rpm(0)  {
    }
  arduino_it_(const ContainerAllocator& _alloc)
    : distance(0)
    , rpm(0)  {
  (void)_alloc;
    }



   typedef int64_t _distance_type;
  _distance_type distance;

   typedef int64_t _rpm_type;
  _rpm_type rpm;





  typedef boost::shared_ptr< ::kumpulan_msgs::arduino_it_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kumpulan_msgs::arduino_it_<ContainerAllocator> const> ConstPtr;

}; // struct arduino_it_

typedef ::kumpulan_msgs::arduino_it_<std::allocator<void> > arduino_it;

typedef boost::shared_ptr< ::kumpulan_msgs::arduino_it > arduino_itPtr;
typedef boost::shared_ptr< ::kumpulan_msgs::arduino_it const> arduino_itConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kumpulan_msgs::arduino_it_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kumpulan_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kumpulan_msgs': ['/home/ainiaalif/project_mobil/src/kumpulan_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kumpulan_msgs::arduino_it_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kumpulan_msgs::arduino_it_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kumpulan_msgs::arduino_it_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7185bd32d30d0999a697641753b76f72";
  }

  static const char* value(const ::kumpulan_msgs::arduino_it_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7185bd32d30d0999ULL;
  static const uint64_t static_value2 = 0xa697641753b76f72ULL;
};

template<class ContainerAllocator>
struct DataType< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kumpulan_msgs/arduino_it";
  }

  static const char* value(const ::kumpulan_msgs::arduino_it_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 distance\n\
int64 rpm\n\
";
  }

  static const char* value(const ::kumpulan_msgs::arduino_it_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arduino_it_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kumpulan_msgs::arduino_it_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kumpulan_msgs::arduino_it_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<int64_t>::stream(s, indent + "  ", v.distance);
    s << indent << "rpm: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUMPULAN_MSGS_MESSAGE_ARDUINO_IT_H
