// Generated by gencpp from file kumpulan_msgs/it_control.msg
// DO NOT EDIT!


#ifndef KUMPULAN_MSGS_MESSAGE_IT_CONTROL_H
#define KUMPULAN_MSGS_MESSAGE_IT_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kumpulan_msgs
{
template <class ContainerAllocator>
struct it_control_
{
  typedef it_control_<ContainerAllocator> Type;

  it_control_()
    : lastRodaKiri(0)
    , lastRodaKanan(0)  {
    }
  it_control_(const ContainerAllocator& _alloc)
    : lastRodaKiri(0)
    , lastRodaKanan(0)  {
  (void)_alloc;
    }



   typedef int64_t _lastRodaKiri_type;
  _lastRodaKiri_type lastRodaKiri;

   typedef int64_t _lastRodaKanan_type;
  _lastRodaKanan_type lastRodaKanan;





  typedef boost::shared_ptr< ::kumpulan_msgs::it_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kumpulan_msgs::it_control_<ContainerAllocator> const> ConstPtr;

}; // struct it_control_

typedef ::kumpulan_msgs::it_control_<std::allocator<void> > it_control;

typedef boost::shared_ptr< ::kumpulan_msgs::it_control > it_controlPtr;
typedef boost::shared_ptr< ::kumpulan_msgs::it_control const> it_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kumpulan_msgs::it_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kumpulan_msgs::it_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kumpulan_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kumpulan_msgs': ['/home/ainiaalif/project_mobil/src/kumpulan_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kumpulan_msgs::it_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kumpulan_msgs::it_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kumpulan_msgs::it_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kumpulan_msgs::it_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kumpulan_msgs::it_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kumpulan_msgs::it_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kumpulan_msgs::it_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60681b7a9d7a45af768b7da63ee97fec";
  }

  static const char* value(const ::kumpulan_msgs::it_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60681b7a9d7a45afULL;
  static const uint64_t static_value2 = 0x768b7da63ee97fecULL;
};

template<class ContainerAllocator>
struct DataType< ::kumpulan_msgs::it_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kumpulan_msgs/it_control";
  }

  static const char* value(const ::kumpulan_msgs::it_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kumpulan_msgs::it_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 lastRodaKiri\n\
int64 lastRodaKanan\n\
";
  }

  static const char* value(const ::kumpulan_msgs::it_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kumpulan_msgs::it_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lastRodaKiri);
      stream.next(m.lastRodaKanan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct it_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kumpulan_msgs::it_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kumpulan_msgs::it_control_<ContainerAllocator>& v)
  {
    s << indent << "lastRodaKiri: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lastRodaKiri);
    s << indent << "lastRodaKanan: ";
    Printer<int64_t>::stream(s, indent + "  ", v.lastRodaKanan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUMPULAN_MSGS_MESSAGE_IT_CONTROL_H
